[workspace]
resolver = "2"

members = [
    "certval",
    "pkiprocmacros",
    "pittv3",
]

[profile.bench]
debug = true

[profile.release]
debug = true

[patch.crates-io]
cms        = { git = "https://github.com/RustCrypto/formats.git" }
const-oid  = { git = "https://github.com/RustCrypto/formats.git" }
der        = { git = "https://github.com/RustCrypto/formats.git" }
der_derive = { git = "https://github.com/RustCrypto/formats.git" }
pkcs1      = { git = "https://github.com/RustCrypto/formats.git" }
pkcs8      = { git = "https://github.com/RustCrypto/formats.git" }
sec1       = { git = "https://github.com/RustCrypto/formats.git" }
spki       = { git = "https://github.com/RustCrypto/formats.git" }
x509-ocsp  = { git = "https://github.com/RustCrypto/formats.git" }
x509-cert  = { git = "https://github.com/RustCrypto/formats.git" }


rsa = { git = "https://github.com/RustCrypto/RSA.git" }
p256 = { git = "https://github.com/RustCrypto/elliptic-curves.git" }
p384 = { git = "https://github.com/RustCrypto/elliptic-curves.git" }

ecdsa = { git = "https://github.com/RustCrypto/signatures.git" }

sha1 = { git = "https://github.com/RustCrypto/hashes.git" }
sha2 = { git = "https://github.com/RustCrypto/hashes.git" }

[patch.'https://github.com/carl-wallace/pqckeys']
pqckeys = { git = "https://github.com/baloo/pqckeys.git", branch = "baloo/pre-releases" }
